<?php
function basr_core_custom_theme_color( $color ){
	$css = '';
	$css .= 'a.portfolio-link:hover ,.portfolio-listing .hentry .portfolio-content .title a:hover ,.portfolio-slider-1 .hentry .portfolio-content .title a:hover ,.portfolio-slider-2 .hentry .portfolio-content .portfolio-link:hover ,.portfolio-slider-3 .hentry .slick-fake-prev ,.portfolio-grid .hentry .portfolio-link:hover ,.portfolio-grid.hover-2 .hentry .portfolio-content .title a ,.portfolio-grid.hover-2 .hentry .portfolio-content .wrap-p-cat a:hover { color: ' . $color . ';}';
	$css .= '.portfolio-slider-2 .slick-slide .hidden-slide:after ,.portfolio-slider-2 .hentry:hover .portfolio-content ,    .portfolio-slider-2 .hentry.first-slide .portfolio-content ,.portfolio-grid.hover-1.no-border .hentry .portfolio-content ,.portfolio-grid.hover-1 .hentry:hover .portfolio-content ,.portfolio-grid.hover-2.no-border .hentry .portfolio-content ,.portfolio-grid.hover-2 .hentry:hover .portfolio-content ,.portfolio-grid.hover-3 .hentry:hover .open-photoswipe:before { border-color: ' . $color . ';}';
	$css .= '    .portfolio-slider-2 .hentry.first-slide .portfolio-content { border-top-color: ' . $color . ';}';
	$css .= '    .portfolio-slider-2 .hentry.first-slide .portfolio-content { border-bottom-color: ' . $color . ';}';
	$css .= '.mCSB_scrollTools .mCSB_dragger .mCSB_dragger_bar ,.single-basr-portfolio .container .portfolio-wrap.style-3 .portfolio-content ,.single-basr-portfolio .container .portfolio-wrap.style-4 .portfolio-content .portfolio-info .portfolio-author,.single-basr-portfolio .container .portfolio-wrap.style-5 .portfolio-content .portfolio-info .portfolio-author ,.single-basr-portfolio .container .portfolio-wrap.style-4 .portfolio-content .portfolio-info .portfolio-author .author .avatar:before,.single-basr-portfolio .container .portfolio-wrap.style-5 .portfolio-content .portfolio-info .portfolio-author .author .avatar:before ,.portfolio-slider-3 .hentry .slick-fake-prev ,.portfolio-slider-3 .hentry .wrap-portfolio-content ,    .portfolio-slider-3 .hentry .wrap-portfolio-content ,.portfolio-grid.hover-4 .hentry .portfolio-content:hover:after,.portfolio-grid.hover-7 .hentry .portfolio-content:hover:after ,.cssload-cube { background-color: ' . $color . ';}';
	return $css;
}